### ISSUE TITLE
Dependency issue installing

### ISSUE THREAD

**Issue by mystique09** [get-eventually/eventually-rs#336]
How do I solve this error when installing the crate?

```nushell
error[E0432]: unresolved import `serde::export`
  --> C:\Users\benji\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\refinery-core-0.3.2\src\runner.rs:11:12
   |
11 | use serde::export::Formatter;
   |            ^^^^^^ could not find `export` in `serde`


For more information about this error, try `rustc --explain E0432`.

error: could not compile `refinery-core` (lib) due to 1 previous error
```

**Comment by mystique09** [comment]
I feel like this is because of serde version, I'm using serde version 1.0.219.

**Comment by ar3s3ru** [comment]
Hi @mystique09, thanks for the report 🫡

Can you share a small reproducible example of your issue?

I also have a feeling it has to do with `serde` version (the crate here is selecting a specific older version, yours is specifying a newer one, cargo is probably downloading the older one).

**Comment by mystique09** [comment]
> Hi [@mystique09](https://github.com/mystique09), thanks for the report 🫡
> 
> Can you share a small reproducible example of your issue?
> 
> I also have a feeling it has to do with `serde` version (the crate here is selecting a specific older version, yours is specifying a newer one, cargo is probably downloading the older one).

I would also mention that I am using nightly rust on my projects, it is private as of now but I made a new [repository](https://github.com/mystique09/eventually-rs-installation-issue) to reproduce the issue.

**Comment by ar3s3ru** [comment]
Thanks for the repo - I could reproduce the issue.

I see you are using `v0.4.0` - which is the latest version published on crates.io. However that version is not quite updated anymore, and other stuff got in the way of stabilizing `v0.5.0`.

My suggestion is to use the latest version on `main` - tested it and it should work:

```toml
[dependecies]
eventually = { version = "0.5.0", features = ["full"], git = "https://github.com/get-eventually/eventually-rs" }
eventually-postgres = { version = "0.5.0", git = "https://github.com/get-eventually/eventually-rs" }
``` 

Can you test that out in your private repository and tell me if it works?
